name: 'JUnit Reporter'
description: 'Report JUnit test results as annotations on Github Pull Request and collect them on remote server'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  token:
    description: 'Used to add check information'
    required: false
    default: ${{ github.token }}
  path:
    description: 'JUnit XML report path in glob format'
    required: false
    default: '**/TEST-*.xml'
  matrix:
    description: 'Matrix context of job'
    required: false
    default: ${{ toJson(matrix) }}
  webhook-url:
    description: 'Specifies the endpoint URL where the JUnit test results will be sent'
    required: false
  webhook-message-size:
    description: 'Specifies the maximum size in bytes of the message sent to the webhook'
    required: false
    default: '917504'
  configuration-url:
    description: 'Used to fetch external configuration. Put empty string to disable.'
    required: false
    default: 'https://c.allegrogroup.com/qyn1owR'
  show:
    description: 'Which tests should be displayed in report. Valid inputs are: "all", "failures", "failures-and-skipped"'
    required: false
    default: 'all'
runs:
  using: 'node12'
  main: 'dist/index.js'
